ALTER TABLE contabancaria 
ADD COLUMN agencia VARCHAR(100) NOT NULL,
ADD COLUMN tipoConta VARCHAR(100) NOT NULL,
ADD COLUMN status VARCHAR(100) NOT NULL,
ADD COLUMN dataCriacao VARCHAR(100) NOT NULL;
